Koduhaldus/Controllers/TeenusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Koduhaldus;
using Koduhaldus.Models;

namespace Koduhaldus.Controllers
{
    public class TeenusController : Controller
    {
        private KoduhaldusEntities db = new KoduhaldusEntities();

        // GET: Teenus
        public ActionResult Index()
        {
            ViewBag.Ostukorv = Ostukorv.Korv;
            return View(db.Teenus.ToList());
        }

        // GET: Teenus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Teenus teenus = db.Teenus.Find(id);
            if (teenus == null)
            {
                return HttpNotFound();
            }
            return View(teenus);
        }

        // GET: Teenus/Create
        public ActionResult Create()

        {
            if (Request.IsAuthenticated)
            {
                
                return View();
            }
            else
            {
               return Redirect ("/");
            }

        }

        // POST: Teenus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,nimetus,liik,tunnihind,korrahind")] Teenus teenus)
        {
            if (ModelState.IsValid)
            {
                db.Teenus.Add(teenus);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(teenus);
        }

        public ActionResult Telli(int? id)
        {
            if (id.HasValue)
            {
                if (!Ostukorv.Korv.Keys.Contains(id.Value))
                    Ostukorv.Korv.Add(id.Value, new OstukorviRida { TeenusId = id ?? 0, Mitu = 0 });
                Ostukorv.Korv[id.Value].Mitu++;
            }
            return RedirectToAction("Index");
        }
        public ActionResult Maha(int? id)
        {
            if (id.HasValue)
            {
                if (Ostukorv.Korv.Keys.Contains(id.Value))
                {
                    Ostukorv.Korv[id.Value].Mitu--;
                    if (Ostukorv.Korv[id.Value].Mitu == 0) Ostukorv.Korv.Remove(id.Value);
                }
            }
            return RedirectToAction("Index");
        }


        // GET: Teenus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Teenus teenus = db.Teenus.Find(id);
            if (teenus == null)
            {
                return HttpNotFound();
            }
            return View(teenus);
        }

        // POST: Teenus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,nimetus,liik,tunnihind,korrahind")] Teenus teenus)
        {
            if (ModelState.IsValid)
            {
                db.Entry(teenus).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(teenus);
        }

        // GET: Teenus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Teenus teenus = db.Teenus.Find(id);
            if (teenus == null)
            {
                return HttpNotFound();
            }
            return View(teenus);
        }

        // POST: Teenus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Teenus teenus = db.Teenus.Find(id);
            db.Teenus.Remove(teenus);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Koduhaldus/Controllers/TelliminesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Koduhaldus;
using Koduhaldus.Models;
using System.ComponentModel.DataAnnotations;

namespace Koduhaldus.Controllers
{
    public class TelliminesController : Controller
    {
        private KoduhaldusEntities db = new KoduhaldusEntities();

        // GET: Tellimines
        public ActionResult Index()
        {
            var tellimines = db.Tellimine.Include(t => t.Kasutaja).Include(t => t.Teenus);
            ViewBag.Ostukorv = Ostukorv.Korv;
            return View(tellimines.ToList());
        }

        // GET: Tellimines/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tellimine tellimine = db.Tellimine.Find(id);
            if (tellimine == null)
            {
                return HttpNotFound();
            }
            return View(tellimine);
        }

        // GET: Tellimines/Create
        public ActionResult Create()
        {
            ViewBag.Ostukorv = Ostukorv.Korv;
            ViewBag.KasutajaID = new SelectList(db.Kasutaja, "Id", "Email");
            //ViewBag.TeenusID = new SelectList(db.Teenus, "id", "nimetus");
            return View();
        }

        // POST: Tellimines/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Aadress,Kuupäev,Kellaaeg,KasutajaID,Telefon")] Tellimine tellimine)
        {
            if (ModelState.IsValid)
            {
                foreach (OstukorviRida or in Ostukorv.Korv.Values)
                {
                    db.Tellimine.Add(new Tellimine { Aadress = tellimine.Aadress, KasutajaID = tellimine.KasutajaID, Kellaaeg = tellimine.Kellaaeg, Kuupäev = tellimine.Kuupäev, Telefon = tellimine.Telefon, TeenusID = or.TeenusId });
                    db.SaveChanges();
                }
                return RedirectToAction("Blogi","Home");
            }
            //
            ViewBag.Ostukorv = Ostukorv.Korv;
            ViewBag.KasutajaID = new SelectList(db.Kasutaja, "Id", "Email", tellimine.KasutajaID);
            ViewBag.TeenusID = new SelectList(db.Teenus, "id", "nimetus", tellimine.TeenusID);
            return View(tellimine);
        }

        // GET: Tellimines/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tellimine tellimine = db.Tellimine.Find(id);
            if (tellimine == null)
            {
                return HttpNotFound();
            }
            ViewBag.KasutajaID = new SelectList(db.Kasutaja, "Id", "Email", tellimine.KasutajaID);
            ViewBag.TeenusID = new SelectList(db.Teenus, "id", "nimetus", tellimine.TeenusID);
            return View(tellimine);
        }

        // POST: Tellimines/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        

        public ActionResult Edit([Bind(Include = "Id,TeenusID,Aadress,Kuupäev,Kellaaeg,KasutajaID,Telefon")] Tellimine tellimine)
        {
            if (ModelState.IsValid)
            {
                
                db.Entry(tellimine).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.KasutajaID = new SelectList(db.Kasutaja, "Id", "Email", tellimine.KasutajaID);
            ViewBag.TeenusID = new SelectList(db.Teenus, "id", "nimetus", tellimine.TeenusID);
            return View("Edit", tellimine);
        }

        // GET: Tellimines/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tellimine tellimine = db.Tellimine.Find(id);
            if (tellimine == null)
            {
                return HttpNotFound();
            }
            return View(tellimine);
        }

        // POST: Tellimines/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tellimine tellimine = db.Tellimine.Find(id);
            db.Tellimine.Remove(tellimine);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Koduhaldus/Views/Teenus/Create.cshtml
@model Koduhaldus.Teenus

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Teenus</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nimetus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nimetus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nimetus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.liik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.liik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.liik, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.tunnihind, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tunnihind, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tunnihind, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.korrahind, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.korrahind, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.korrahind, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Koduhaldus/Views/Teenus/Delete.cshtml
@model Koduhaldus.Teenus

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Teenus</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nimetus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nimetus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.liik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.liik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tunnihind)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tunnihind)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.korrahind)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.korrahind)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Koduhaldus/Views/Teenus/Details.cshtml
@model Koduhaldus.Teenus

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Teenus</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nimetus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nimetus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.liik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.liik)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.tunnihind)
        </dt>*@

        @*<dd>
            @Html.DisplayFor(model => model.tunnihind)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.korrahind)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.korrahind)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Koduhaldus/Views/Teenus/Edit.cshtml
@model Koduhaldus.Teenus

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Teenus</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.nimetus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nimetus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nimetus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.liik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.liik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.liik, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.tunnihind, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tunnihind, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tunnihind, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.korrahind, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.korrahind, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.korrahind, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Koduhaldus/Views/Teenus/Index.cshtml
@model IEnumerable<Koduhaldus.Teenus>
@using Koduhaldus.Models





@{
    ViewBag.Title = "Teenuste tellimine";
}

<div class="row">
    <div class="col-md-8">

        <br />
        <br />
        <br />
        <center>
            <img src="~/Images/telli.png" style="width:500px;height:256px;">
        </center>
        <h2>Telli kohe!</h2>

        <h3>@ViewBag.Message</h3>

        @{
            Kasutaja kasutaja = Kasutaja.ByEmail(User.Identity.Name);

            if (kasutaja?.KasAdmin ?? false)
            {
            <p>

                @Html.ActionLink("Create New", "Create")
            </p>

            }

        }

        @*{
        <p>
            @Html.ActionLink("Create New", "Create")
        </p>
        }*@
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.nimetus)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.liik)
                </th>
                @*<th>
                    @Html.DisplayNameFor(model => model.tunnihind)
                </th>*@
                <th>
                    @Html.DisplayNameFor(model => model.korrahind)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.nimetus)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.liik)
                </td>
                @*<td>
                    @Html.DisplayFor(modelItem => item.tunnihind)
                </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.korrahind)
                </td>


                <h3>@ViewBag.Message</h3>

                @{
                    if (kasutaja?.KasAdmin ?? false)
                    {
                    <td>

                        @Html.ActionLink("Edit", "Edit", new { id = item.id })
                    </td>
                    <td>
                        @Html.ActionLink("Details", "Details", new { id = item.id })
                    </td>
                    <td>
                        @Html.ActionLink("Delete", "Delete", new { id = item.id })
                    </td>


                    }

                }



                <td>
                   
                    @Html.ActionLink("Tellin", "Telli", new { id = item.id })


                </td>
            </tr>

                    }

        </table>

        <h2>Sinu ostukorv</h2>
        <table>
            @foreach (OstukorviRida or in ViewBag.Ostukorv.Values)
            {
            <tr>
                <td>
                    @or.Teenus.nimetus
                </td>
                <td>@or.Mitu</td>

                <td>|</td>
                <td>@Html.ActionLink("Eemalda", "Maha", new { id = or.TeenusId })</td>


            </tr>
            }


        </table>
        @{
            IEnumerable<OstukorviRida> korv = ViewBag.Ostukorv.Values;
            var summa = korv.Select(x => x.Teenus.korrahind * x.Mitu).Sum();
        <p>Ostukorvi summa: @summa  EUR</p>
            }

            @{if (summa > 0)
                {
          @Html.ActionLink("Kinnita tellimus ja sisesta andmed", "Create", "Tellimines")
                    } }
        @*<div class="form-group">
            @Html.LabelFor(modelTellimine => modelTellimine.Aadress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Aadress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Aadress, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @{if (kasutaja?.KasAdmin ?? false)
            {
        <td>

            @Html.ActionLink("Vaata tehtud tellimusi", "Index", "Tellimines"@*, new { id = item.id }*@)
        </td>
                }
            }
    </div>
</div>