Koduhaldus/Controllers/PostitusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Koduhaldus;
using System.IO;
namespace Koduhaldus
{
    partial class Postitus
    {
        public string SisuLyhike => (Sisu ?? "").Length < 200 ? Sisu : Sisu.Substring(0, 200);
    }
}

namespace Koduhaldus.Controllers
{
    public class PostitusController : Controller
    {
        private KoduhaldusEntities db = new KoduhaldusEntities();

        // GET: Postitus
        public ActionResult Index()
        {
            var postitus = db.Postitus.Include(p => p.Kasutaja).Include(p => p.Kategooria);
            return View(postitus.ToList());
        }




        // GET: Postitus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)

            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Postitus postitus = db.Postitus.Find(id);
            if (postitus == null)
            {
                return HttpNotFound();
            }

            Kasutaja u = db.Kasutaja.Where(x => x.Email == User.Identity.Name).SingleOrDefault();
            if (u != null)
            {
                ViewBag.NewKommentaar = new Kommentaar { PostitusId = id.Value, KasutajaId = u.Id, Kuupäev = DateTime.Now, Sisu = "" };
                return View(postitus);
            }
            //else return RedirectToAction("Index");
            else
            {
                ViewBag.NewKommentaar = null;
                return View(postitus);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Details([Bind(Include = "Id,Pealkiri,Sisu,Kuupäev,KasutajaId,KategooriaId,PostitusId")] Kommentaar kommentaar)
        {


            if (ModelState.IsValid && kommentaar.Sisu != "")
            {
                db.Kommentaar.Add(kommentaar);
                db.SaveChanges();
                return RedirectToAction("Details");
            }

            return View(db.Postitus.Find(kommentaar.PostitusId));
        }


        // GET: Postitus/Create
        public ActionResult Create(int? id)
        {

            Kasutaja u = db.Kasutaja.Where(x => x.Email == User.Identity.Name).SingleOrDefault();

       
            if (u?.KasAdmin ?? false)
            {
                Postitus p = new Postitus();

                p.Kuupäev = DateTime.Now.Date;


                ViewBag.KasutajaNimi = db.Kasutaja.Where(x => x.Email == User.Identity.Name).SingleOrDefault()?.Nimi;
                ViewBag.KategooriaId = new SelectList(db.Kategooria, "Id", "Nimetus");
                ViewBag.KasutajaId = new SelectList(db.Kasutaja, "Id", "Nimi", p.KasutajaId);
                return View(p);
            }
            else return RedirectToAction("Index");
        }

        // POST: Postitus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Pealkiri,Sisu,Kuupäev,KasutajaId,KategooriaId")] Postitus postitus)
        {
            if (ModelState.IsValid)
            {
                db.Postitus.Add(postitus);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.KasutajaId = new SelectList(db.Kasutaja, "Id", "Email", postitus.KasutajaId);
            ViewBag.KategooriaId = new SelectList(db.Kategooria, "Id", "Nimetus", postitus.KategooriaId);
            return View(postitus);
        }

        // GET: Postitus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Postitus postitus = db.Postitus.Find(id);
            if (postitus == null)
            {
                return HttpNotFound();
            }
            ViewBag.KasutajaId = new SelectList(db.Kasutaja, "Id", "Email", postitus.KasutajaId);
            ViewBag.KategooriaId = new SelectList(db.Kategooria, "Id", "Nimetus", postitus.KategooriaId);
            return View(postitus);
        }

        // POST: Postitus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Pealkiri,Sisu,Kuupäev,KasutajaId,KategooriaId")] Postitus postitus)
        {
            if (ModelState.IsValid)
            {
                db.Entry(postitus).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.KasutajaId = new SelectList(db.Kasutaja, "Id", "Email", postitus.KasutajaId);
            ViewBag.KategooriaId = new SelectList(db.Kategooria, "Id", "Nimetus", postitus.KategooriaId);
            return View(postitus);
        }

        // GET: Postitus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Postitus postitus = db.Postitus.Find(id);
            if (postitus == null)
            {
                return HttpNotFound();
            }
            return View(postitus);
        }

        // POST: Postitus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Postitus postitus = db.Postitus.Find(id);
            db.Postitus.Remove(postitus);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult CreatePicture(HttpPostedFileBase file)
        {
            if (file != null && file.ContentLength > 0)
                try
                {
                    string path = Path.Combine(Server.MapPath("~/Images"),
                    Path.GetFileName(file.FileName));
                    file.SaveAs(path);
                    ViewBag.Message = "File uploaded successfully";
                }
                catch (Exception ex)
                {
                    ViewBag.Message = "ERROR:" + ex.Message.ToString();
                }
            else
            {
                ViewBag.Message = "You have not specified a file.";
            }
            return RedirectToAction("Create");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Koduhaldus/Controllers/TeenusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Koduhaldus;
using Koduhaldus.Models;

namespace Koduhaldus.Controllers
{
    public class TeenusController : Controller
    {
        private KoduhaldusEntities db = new KoduhaldusEntities();

        // GET: Teenus
        public ActionResult Index()
        {
            ViewBag.Ostukorv = Ostukorv.Korv;
            return View(db.Teenus.ToList());
        }

        // GET: Teenus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Teenus teenus = db.Teenus.Find(id);
            if (teenus == null)
            {
                return HttpNotFound();
            }
            return View(teenus);
        }

        // GET: Teenus/Create
        public ActionResult Create()

        {
            if (Request.IsAuthenticated)
            {
                
                return View();
            }
            else
            {
               return Redirect ("/");
            }

        }

        // POST: Teenus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,nimetus,liik,tunnihind,korrahind")] Teenus teenus)
        {
            if (ModelState.IsValid)
            {
                db.Teenus.Add(teenus);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(teenus);
        }

        public ActionResult Telli(int? id)
        {
            if (id.HasValue)
            {
                if (!Ostukorv.Korv.Keys.Contains(id.Value))
                    Ostukorv.Korv.Add(id.Value, new OstukorviRida { TeenusId = id ?? 0, Mitu = 0 });
                Ostukorv.Korv[id.Value].Mitu++;
            }
            return RedirectToAction("Index");
        }
        public ActionResult Maha(int? id)
        {
            if (id.HasValue)
            {
                if (Ostukorv.Korv.Keys.Contains(id.Value))
                {
                    Ostukorv.Korv[id.Value].Mitu--;
                    if (Ostukorv.Korv[id.Value].Mitu == 0) Ostukorv.Korv.Remove(id.Value);
                }
            }
            return RedirectToAction("Index");
        }


        // GET: Teenus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Teenus teenus = db.Teenus.Find(id);
            if (teenus == null)
            {
                return HttpNotFound();
            }
            return View(teenus);
        }

        // POST: Teenus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,nimetus,liik,tunnihind,korrahind")] Teenus teenus)
        {
            if (ModelState.IsValid)
            {
                db.Entry(teenus).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(teenus);
        }

        // GET: Teenus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Teenus teenus = db.Teenus.Find(id);
            if (teenus == null)
            {
                return HttpNotFound();
            }
            return View(teenus);
        }

        // POST: Teenus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Teenus teenus = db.Teenus.Find(id);
            db.Teenus.Remove(teenus);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Koduhaldus/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -  MAJASOKK </> </title>
    @Styles.Render("~/Content/css")
    <link rel="stylesheet" href="@Url.Content("~/Content/jquery-ui/jquery-ui.min.css")" />
    @Scripts.Render("~/bundles/modernizr")
  
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MAJASOKK", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Esileht", "Index", "Home")</li>
                    <li>@Html.ActionLink("Blogi", "Index", "Postitus")</li>
                    <li>@Html.ActionLink("Teenuste tellimine", "Index", "Teenus")</li>



                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <br />
    <br />
    <br />
    <div class="container body-content">
        <br />
        <br />
        <br />
        <table style="width:100%; border:none; border-collapse: collapse;" cellspacing="0" cellpadding="0">
            <tr>
                <td>
                    @RenderBody()
                </td>
                <td style="background-color:azure; width: 20px">

                    <div style="padding: 0px 20px; font-family:Verdana, Times, serif; font-size:large">
                        <br />
                        <br />
                        <br />

                        Helista MAJASOKULE
                        tel. 322 233
                    </div>
                </td>
            <tr>
        </table>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MAJASOKK</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/jquery")

    <script src="@Url.Content("~/Content/jquery-ui/jquery-ui.min.js")"></script>
    @Styles.Render("~/Content/jquety-ui/images")
    @Scripts.Render("~/bundles/jqueryui")

    @*@Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
    <script>
        $(document).ready(function () {

            $('.datepicker').datepicker({
                dateFormat: 'dd.mm.yy',
               startDate: Date.now
            });

        });

    </script>
    <script>
        /* Estonian initialisation for the jQuery UI date picker plugin. */
        /* Written by Mart Sõmermaa (mrts.pydev at gmail com). */
        (function (factory) {
            if (typeof define === "function" && define.amd) {
                // AMD. Register as an anonymous module.
                define(["../widgets/datepicker"], factory);
            } else {
                // Browser globals
                factory(jQuery.datepicker);
            }
        }(function (datepicker) {
            datepicker.regional.et = {
                closeText: "Sulge",
                prevText: "Eelnev",
                nextText: "Järgnev",
                currentText: "Täna",
                monthNames: ["Jaanuar", "Veebruar", "Märts", "Aprill", "Mai", "Juuni",
                    "Juuli", "August", "September", "Oktoober", "November", "Detsember"],
                monthNamesShort: ["Jaan", "Veebr", "Märts", "Apr", "Mai", "Juuni",
                    "Juuli", "Aug", "Sept", "Okt", "Nov", "Dets"],
                dayNames: [
                    "Pühapäev",
                    "Esmaspäev",
                    "Teisipäev",
                    "Kolmapäev",
                    "Neljapäev",
                    "Reede",
                    "Laupäev"
                ],
                dayNamesShort: ["Pühap", "Esmasp", "Teisip", "Kolmap", "Neljap", "Reede", "Laup"],
                dayNamesMin: ["P", "E", "T", "K", "N", "R", "L"],
                weekHeader: "näd",
                dateFormat: "dd.mm.yy",
                firstDay: 1,
                isRTL: false,
                showMonthAfterYear: false,
                yearSuffix: ""
            };
            datepicker.setDefaults(datepicker.regional.et);
            return datepicker.regional.et;
        }));
    </script>




    @*@Scripts.Render("~/bundles/jquery")*@
    @*@Scripts.Render("~/bundles/bootstrap")*@
    @*@RenderSection("scripts", required: false)*@
</body>
</html>