Koduhaldus/Controllers/KommentaarsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Koduhaldus;

namespace Koduhaldus.Controllers
{
    public class KommentaarsController : Controller
    {
        private KoduhaldusEntities db = new KoduhaldusEntities();

        // GET: Kommentaars
        public ActionResult Index()
        {
            var kommentaar = db.Kommentaar.Include(k => k.Kasutaja).Include(k => k.Postitus);
            return View(kommentaar.ToList());
        }

        // GET: Kommentaars/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kommentaar kommentaar = db.Kommentaar.Find(id);
            if (kommentaar == null)
            {
                return HttpNotFound();
            }
            return View(kommentaar);
        }
        //SingleOrDefault()?.Nimi
        // GET: Kommentaars/Create
        public ActionResult Create(int? id)
        {
            if (id == null) return HttpNotFound();

            Kasutaja u = db.Kasutaja.Where(x => x.Email == User.Identity.Name).SingleOrDefault();  
          
           
            Kommentaar k = new Kommentaar();
            k.PostitusId = id.Value;
            k.Kuupäev = DateTime.Now.Date;
            k.KasutajaId = u?.Id ?? 0; 
            ViewBag.PostitusId = new SelectList(db.Postitus, "Id", "Pealkiri",k.PostitusId);
            ViewBag.KasutajaId = new SelectList(db.Kasutaja, "Id", "Nimi", k.KasutajaId);
            return View(k);
            //return View(Postitus);
        }

        // POST: Kommentaars/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,PostitusId,KasutajaId,Kuupäev,Sisu")] Kommentaar kommentaar)
        {
            if (ModelState.IsValid)
            {
                db.Kommentaar.Add(kommentaar);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.KasutajaId = new SelectList(db.Kasutaja, "Id", "Email", kommentaar.KasutajaId);
            ViewBag.PostitusId = new SelectList(db.Postitus, "Id", "Pealkiri", kommentaar.PostitusId);
            return View(kommentaar);
        }

        // GET: Kommentaars/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kommentaar kommentaar = db.Kommentaar.Find(id);
            if (kommentaar == null)
            {
                return HttpNotFound();
            }
            ViewBag.KasutajaId = new SelectList(db.Kasutaja, "Id", "Email", kommentaar.KasutajaId);
            ViewBag.PostitusId = new SelectList(db.Postitus, "Id", "Pealkiri", kommentaar.PostitusId);
            return View(kommentaar);
        }

        // POST: Kommentaars/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,PostitusId,KasutajaId,Kuupäev,Sisu")] Kommentaar kommentaar)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kommentaar).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.KasutajaId = new SelectList(db.Kasutaja, "Id", "Email", kommentaar.KasutajaId);
            ViewBag.PostitusId = new SelectList(db.Postitus, "Id", "Pealkiri", kommentaar.PostitusId);
            return View(kommentaar);
        }

        // GET: Kommentaars/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kommentaar kommentaar = db.Kommentaar.Find(id);
            if (kommentaar == null)
            {
                return HttpNotFound();
            }
            return View(kommentaar);
        }

        // POST: Kommentaars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Kommentaar kommentaar = db.Kommentaar.Find(id);
            db.Kommentaar.Remove(kommentaar);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Koduhaldus/Controllers/MeeldiminesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Koduhaldus;

namespace Koduhaldus.Controllers
{
    public class MeeldiminesController : Controller
    {
        private KoduhaldusEntities db = new KoduhaldusEntities();

        // GET: Meeldimines
        public ActionResult Index()
        {
            var meeldimines = db.Meeldimine.Include(m => m.Kasutaja).Include(m => m.Postitus);
            return View(meeldimines.ToList());
        }

        // GET: Meeldimines/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Meeldimine meeldimine = db.Meeldimine.Find(id);
            if (meeldimine == null)
            {
                return HttpNotFound();
            }
            return View(meeldimine);
        }

        // GET: Meeldimines/Create
        public ActionResult Create()
        {
            //ViewBag.KasutajaNimi = db.Kasutaja.Where(x => x.Email == User.Identity.Name).SingleOrDefault()?.Nimi;
            ViewBag.KasutajaId = new SelectList(db.Kasutaja, "Id", "Email");
            ViewBag.PostitusId = new SelectList(db.Postitus, "Id", "Pealkiri");
            return View();
        }

        // POST: Meeldimines/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,PostitusId,KasutajaId,Hinne")] Meeldimine meeldimine)
        {
            if (ModelState.IsValid)
            {
                db.Meeldimine.Add(meeldimine);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.KasutajaId = new SelectList(db.Kasutaja, "Id", "Email", meeldimine.KasutajaId);
            ViewBag.PostitusId = new SelectList(db.Postitus, "Id", "Pealkiri", meeldimine.PostitusId);
            return View(meeldimine);
        }

        // GET: Meeldimines/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Meeldimine meeldimine = db.Meeldimine.Find(id);
            if (meeldimine == null)
            {
                return HttpNotFound();
            }
            ViewBag.KasutajaId = new SelectList(db.Kasutaja, "Id", "Email", meeldimine.KasutajaId);
            ViewBag.PostitusId = new SelectList(db.Postitus, "Id", "Pealkiri", meeldimine.PostitusId);
            return View(meeldimine);
        }

        // POST: Meeldimines/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,PostitusId,KasutajaId,Hinne")] Meeldimine meeldimine)
        {
            if (ModelState.IsValid)
            {
                db.Entry(meeldimine).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.KasutajaId = new SelectList(db.Kasutaja, "Id", "Email", meeldimine.KasutajaId);
            ViewBag.PostitusId = new SelectList(db.Postitus, "Id", "Pealkiri", meeldimine.PostitusId);
            return View(meeldimine);
        }

        // GET: Meeldimines/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Meeldimine meeldimine = db.Meeldimine.Find(id);
            if (meeldimine == null)
            {
                return HttpNotFound();
            }
            return View(meeldimine);
        }

        // POST: Meeldimines/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Meeldimine meeldimine = db.Meeldimine.Find(id);
            db.Meeldimine.Remove(meeldimine);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Koduhaldus/Controllers/PostitusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Koduhaldus;
using System.IO;
namespace Koduhaldus
{
    partial class Postitus
    {
        public string SisuLyhike => (Sisu ?? "").Length < 200 ? Sisu : Sisu.Substring(0, 200);
    }
}

namespace Koduhaldus.Controllers
{
    public class PostitusController : Controller
    {
        private KoduhaldusEntities db = new KoduhaldusEntities();

        // GET: Postitus
        public ActionResult Index()
        {
            var postitus = db.Postitus.Include(p => p.Kasutaja).Include(p => p.Kategooria);
            return View(postitus.ToList());
        }




        // GET: Postitus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)

            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Postitus postitus = db.Postitus.Find(id);
            if (postitus == null)
            {
                return HttpNotFound();
            }

            Kasutaja u = db.Kasutaja.Where(x => x.Email == User.Identity.Name).SingleOrDefault();
            if (u != null)
            {
                ViewBag.NewKommentaar = new Kommentaar { PostitusId = id.Value, KasutajaId = u.Id, Kuupäev = DateTime.Now, Sisu = "" };
                return View(postitus);
            }
            //else return RedirectToAction("Index");
            else
            {
                ViewBag.NewKommentaar = null;
                return View(postitus);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Details([Bind(Include = "Id,Pealkiri,Sisu,Kuupäev,KasutajaId,KategooriaId,PostitusId")] Kommentaar kommentaar)
        {


            if (ModelState.IsValid && kommentaar.Sisu != "")
            {
                db.Kommentaar.Add(kommentaar);
                db.SaveChanges();
                return RedirectToAction("Details");
            }

            return View(db.Postitus.Find(kommentaar.PostitusId));
        }


        // GET: Postitus/Create
        public ActionResult Create(int? id)
        {

            Kasutaja u = db.Kasutaja.Where(x => x.Email == User.Identity.Name).SingleOrDefault();

       
            if (u?.KasAdmin ?? false)
            {
                Postitus p = new Postitus();

                p.Kuupäev = DateTime.Now.Date;


                ViewBag.KasutajaNimi = db.Kasutaja.Where(x => x.Email == User.Identity.Name).SingleOrDefault()?.Nimi;
                ViewBag.KategooriaId = new SelectList(db.Kategooria, "Id", "Nimetus");
                ViewBag.KasutajaId = new SelectList(db.Kasutaja, "Id", "Nimi", p.KasutajaId);
                return View(p);
            }
            else return RedirectToAction("Index");
        }

        // POST: Postitus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Pealkiri,Sisu,Kuupäev,KasutajaId,KategooriaId")] Postitus postitus)
        {
            if (ModelState.IsValid)
            {
                db.Postitus.Add(postitus);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.KasutajaId = new SelectList(db.Kasutaja, "Id", "Email", postitus.KasutajaId);
            ViewBag.KategooriaId = new SelectList(db.Kategooria, "Id", "Nimetus", postitus.KategooriaId);
            return View(postitus);
        }

        // GET: Postitus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Postitus postitus = db.Postitus.Find(id);
            if (postitus == null)
            {
                return HttpNotFound();
            }
            ViewBag.KasutajaId = new SelectList(db.Kasutaja, "Id", "Email", postitus.KasutajaId);
            ViewBag.KategooriaId = new SelectList(db.Kategooria, "Id", "Nimetus", postitus.KategooriaId);
            return View(postitus);
        }

        // POST: Postitus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Pealkiri,Sisu,Kuupäev,KasutajaId,KategooriaId")] Postitus postitus)
        {
            if (ModelState.IsValid)
            {
                db.Entry(postitus).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.KasutajaId = new SelectList(db.Kasutaja, "Id", "Email", postitus.KasutajaId);
            ViewBag.KategooriaId = new SelectList(db.Kategooria, "Id", "Nimetus", postitus.KategooriaId);
            return View(postitus);
        }

        // GET: Postitus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Postitus postitus = db.Postitus.Find(id);
            if (postitus == null)
            {
                return HttpNotFound();
            }
            return View(postitus);
        }

        // POST: Postitus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Postitus postitus = db.Postitus.Find(id);
            db.Postitus.Remove(postitus);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult CreatePicture(HttpPostedFileBase file)
        {
            if (file != null && file.ContentLength > 0)
                try
                {
                    string path = Path.Combine(Server.MapPath("~/Images"),
                    Path.GetFileName(file.FileName));
                    file.SaveAs(path);
                    ViewBag.Message = "File uploaded successfully";
                }
                catch (Exception ex)
                {
                    ViewBag.Message = "ERROR:" + ex.Message.ToString();
                }
            else
            {
                ViewBag.Message = "You have not specified a file.";
            }
            return RedirectToAction("Create");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Koduhaldus/Views/Postitus/Delete.cshtml
@model Koduhaldus.Postitus

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Postitus</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Kasutaja.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kasutaja.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kategooria.Nimetus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kategooria.Nimetus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pealkiri)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pealkiri)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sisu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sisu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kuupäev)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kuupäev)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Koduhaldus/Views/Postitus/Details.cshtml
@model Koduhaldus.Postitus
@using Koduhaldus.Models



@{
    ViewBag.Title = "Details";
}

@*<h2>Details</h2>*@

<dv>
    @*<h4>Postitus</h4>*@

    <hr />
    <dl class="dl-horizontal">
        @*<dt>
                @Html.DisplayNameFor(model => model.Kasutaja.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Kasutaja.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Kategooria.Nimetus)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Kategooria.Nimetus)
            </dd>*@

        @*<dt>
                @Html.DisplayNameFor(model => model.Pealkiri)
            </dt>*@

        <dd>
            <h4>@Html.DisplayFor(model => model.Pealkiri)</h4>
        </dd>

        @*<dt>
                @Html.DisplayNameFor(model => model.Sisu)
            </dt>*@

        <dd>
            <br>
            <br>

            @*@{string näita = Model.Sisu.Replace("\n", "<br />");}*@
            <span style="white-space: pre-line">@Model.Sisu</span>

            @*<p>@näita</p>*@


            @*@Html.DisplayFor(model => model.Sisu) //kui ei tööta, pane see tagasi*@
        </dd>
        <br>
        <br>
        <dt>
            @Html.DisplayNameFor(model => model.Kuupäev)

        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.Kuupäev)*@
            @{
                var kuupäev = Model.Kuupäev?.ToString("dd.MMMM.yyyy");
                <p>@kuupäev</p>
            }
        </dd>

        <br>
        @*<a href="@Url.Action("Create", "Meeldimines")" title="LIKE!">
                <img src="..\..\Images\Like.jpg" style="width:30px;height:30px;">
            </a>*@
        <br>
        <br>
        <h4>Kommentaarid:</h4>

        @foreach (var item in Model.Kommentaar)
        {

            <dt>
                @Html.DisplayFor(modelItem => item.Kasutaja.Nimi)
            </dt>
            <dd>
                <span style="white-space: pre-line">@item.Sisu</span>
                @*@Html.DisplayFor(modelItem => item.Sisu)*@
            </dd>
        }
        @if (ViewBag.NewKommentaar != null)
        {
            using (Html.BeginForm())
            {
                Kommentaar kommentaar = ViewBag.NewKommentaar;
                @Html.AntiForgeryToken()

                <br>
                if (Request.IsAuthenticated)
                {
                    <div class="form-horizontal">
                        <h4>Sisesta kommentaar</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => kommentaar.PostitusId)
                        @*@Html.HiddenFor(model => model.KasutajaId)*@
                        @Html.HiddenFor(model => kommentaar.Kuupäev)

                        @*<div class="form-group">*@
                        @*@Html.LabelFor(model => model.PostitusId, "PostitusId", htmlAttributes: new { @class = "control-label col-md-2" })*@
                        @*<div class="col-md-10">*@
                        @*@Html.DropDownList("PostitusId", null, htmlAttributes: new { @class = "form-control" })*@
                        @*@Html.ValidationMessageFor(model => model.PostitusId, "", new { @class = "text-danger" })*@
                        @*</div>*@
                    </div>

                    @*<div class="form-group">
                            @Html.LabelFor(model => model.KasutajaId, "KasutajaId", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("KasutajaId", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.KasutajaId, "", new { @class = "text-danger" })


                        @*</div>*@

                    @*<div class="form-group">
                              @Html.LabelFor(model => model.Kuupäev, htmlAttributes: new { @class = "control-label col-md-2" })
                              <div class="col-md-10">
                                  @Html.EditorFor(model => model.Kuupäev, new { htmlAttributes = new { @class = "form-control" } })
                                  @Html.ValidationMessageFor(model => model.Kuupäev, "", new { @class = "text-danger" })

                            </div>
                        </div>*@

                    <div class="form-group">
                        @Html.HiddenFor(model => kommentaar.KasutajaId)
                        @Html.LabelFor(model => kommentaar.Sisu, htmlAttributes: new { @class = "control-label col-md-2" })


                        <div class="col-md-10">
                            @*@Html.EditorFor(model => kommentaar.Sisu, new { htmlAttributes = new { @class = "control-label col-md-2" } })*@
                            @Html.TextAreaFor(model => kommentaar.Sisu, new { style = "width:1000px; height:600px;" })
                            @Html.ValidationMessageFor(model => kommentaar.Sisu, "", new { @class = "text-danger" })


                        </div>
                    </div>


                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Lisa kommentaar" class="btn btn-default" />
                        </div>
                    </div>
                    @*</div>*@
                }
            }
        }





    </dl>
    </div>
    @{
        Kasutaja kasutaja = Kasutaja.ByEmail(User.Identity.Name);

        if (kasutaja?.KasAdmin ?? false)
        {
    <p>

        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>

        }

    }
    @*<p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>*@

Koduhaldus/Views/Postitus/Index.cshtml
@model IEnumerable<Koduhaldus.Postitus>


@{
    ViewBag.Title = "Index";
}




<div class="row">
    <div class="col-md-13">

        <br />
        <br />
        <br />
        <center>
            <img src="~/Images/blogi.png" style="width:500px;height:256px;">
        </center>
            <h2>Majasokk kirjutab!</h2>
  
        @{
            Kasutaja kasutaja = Kasutaja.ByEmail(User.Identity.Name);

            if (kasutaja?.KasAdmin ?? false)
            {
                <p>

                   @Html.ActionLink("Create New", "Create")
                </p>

            }

        }

          

            <table class="table">
                @*<tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Kasutaja.Email)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Kategooria.Nimetus)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Pealkiri)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Sisu)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Kuupäev)
                    </th>
                    <th></th>
                </tr>*@

                @foreach (var item in Model)
                {
                <tr>
                    <td>
                        @*@Html.DisplayFor(modelItem => item.Kasutaja.Email)*@
                    </td>
                    <td>
                        @*@Html.DisplayFor(modelItem => item.Kategooria.Nimetus)
                    </td>*@
                    <td>
                        <h4> @Html.DisplayFor(modelItem => item.Pealkiri)</h4>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SisuLyhike)
                        @Html.ActionLink("Loe edasi", "Details", new { id = item.Id })
                    </td>
                    <td>
                        @*@Html.DisplayFor(modelItem => item.Kuupäev)*@
                        @{ 
                            var kuupäev  =  item.Kuupäev?.ToString("dd.MMMM.yyyy");
                            <p>@kuupäev</p>
                         }
                    </td>
                    @*@if (Request.IsAuthenticated)
                    {


                    <td>
                        @Html.ActionLink("Kommenteeri", $"Create/{item.Id}", "Kommentaars")

                    </td>
                    }*@
                    <td>
                        @*<button type="button">LIKE!</button>*@
                        @*<input type="button" title="LIKE!" value="LIKE!" onclick="location.href='@Url.Action("Create", "Meeldimines")'" />*@



                    </td>
                    @{
                        //Kasutaja kasutaja1 = Kasutaja.ByEmail(User.Identity.Name);

                        if (kasutaja?.KasAdmin ?? false)
                        {
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.Id })

                            </td>

                        }

                    }
                
                    

                        

                    
            


                </tr>
        }

            </table>
    </div>
</div>

Koduhaldus/Views/Postitus/ShortPost.cshtml
@{
    Layout = "~/Views/Postitus/Index.cshtml";
}